### ISSUE TITLE
Background color not covering background anymore

### ISSUE THREAD

**Issue by voltaek** [tulios/json-viewer#268]
Plugin v0.18.0, Chrome v87.0.4280.66, Windows Server 2019 Standard v1809 (Windows 10 equivalent).

I recently clicked the Update Extensions button (under Extensions when in Developer Mode) in Chrome the other day, and then this issue showed up, so I suspect I was running an older version of the extension for awhile.

Now when a page JSON loads up the background color only covers down to where the content is, instead of the entire background of the page like it used to do. This makes the buttons along the right difficult to see, as they are styled with the intention of being overtop a dark background, plus the obvious white screen instead of dark like I expect with a dark theme. You can see in my attached image that I'm hovering over one of the buttons that would normally be almost impossible to see.

Taking a quick look at the styling, it looks like adding `min-height: 100vh;` to the `.CodeMirror-scroll` CSS class would solve the issue. I'd submit a PR, but I can't seem to locate where this CSS rule is located in the styling files.

![json_ext_issue](https://user-images.githubusercontent.com/7809420/100114121-167c6300-2e3f-11eb-93f4-bcb98b17fd14.png)

**Comment by jomiva** [comment]
![image](https://user-images.githubusercontent.com/48603039/100293212-55064080-2f59-11eb-9cd4-55a1a38f4b57.png)
It's happening to me aswell

**Comment by silviohfc** [comment]
> Taking a quick look at the styling, it looks like adding `min-height: 100vh;` to the `.CodeMirror-scroll` CSS class would solve the issue. I'd submit a PR, but I can't seem to locate where this CSS rule is located in the styling files.

Thanks for the hint, i'm having the same problem.

**Comment by voltaek** [comment]
Since I didn't mention this explicitly in my original post, my workaround is to add the styling adjustment I mentioned into the **Custom Style** section of the plugin's options.
```css
/* Add to "Custom Style" section of the plugin's Options page */
.CodeMirror-scroll {
  min-height: 100vh;
}
```

**Comment by voltaek** [comment]
Looks like [a PR](https://github.com/tulios/json-viewer/pull/267) has been merged that fixes this issue, but an update to the extension has not been pushed out, yet.
Their fix is to add this:
```css
body, html {
    height: 100%;
}
```
While we wait for a release, you can add the fix to the **Custom Style** section of the plugin's Options, same as I'd done with my quick-fix styling.

**Comment by maviniciuus** [comment]
![image](https://user-images.githubusercontent.com/24211410/102675241-649f3080-4177-11eb-9366-9c43ed180dba.png)

```css
html,
body {
	height: 100%;
}

.CodeMirror {
	min-height: 100%;
  font-family: monaco, Consolas, Menlo, Courier, monospace;
  font-size: 16px;
  line-height: 1.5em;
}
```
